const states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

const grievanceOptions = {
  Sanitation: {
    "Garbage Collection": [
      "Missed Pickup",
      "Delayed Service",
      "Overflowing Bins",
      "Other",
    ],
    "Drainage Issue": [
      "Clogged Drain",
      "Water Logging",
      "Broken Cover",
      "Other",
    ],
    "Public Toilets": ["Unhygienic", "Locked", "No Water Supply", "Other"],
    Other: ["Other"],
  },
  Water: {
    "No Water Supply": ["Morning", "Evening", "Complete Outage", "Other"],
    Leakage: ["Pipelines", "Overhead Tank", "Street Leakage", "Other"],
    "Water Quality": ["Dirty Water", "Smell in Water", "Color Issues", "Other"],
    Other: ["Other"],
  },
  Electricity: {
    "Power Cut": ["Unscheduled", "Prolonged", "Fluctuation", "Other"],
    "Street Lights": ["Not Working", "Flickering", "Broken Pole", "Other"],
    "Meter Issues": [
      "Reading Discrepancy",
      "Broken Meter",
      "Unauthorized Usage",
      "Other",
    ],
    Other: ["Other"],
  },
  Roads: {
    Potholes: ["Small", "Large", "Frequent", "Other"],
    "Footpath Damage": [
      "Tiles Missing",
      "Encroachments",
      "No Railings",
      "Other",
    ],
    "Traffic Signals": [
      "Not Working",
      "Not Installed",
      "Malfunctioning",
      "Other",
    ],
    Other: ["Other"],
  },
  WasteManagement: {
    "E-Waste": ["No Pickup", "Dumping in Open", "Other"],
    "Construction Debris": ["Not Cleared", "Unauthorized Dumping", "Other"],
    "Medical Waste": ["Hazardous Exposure", "Improper Disposal", "Other"],
    Other: ["Other"],
  },
  Others: {
    Other: ["Other"],
  },
};

export { states, grievanceOptions };
